"""empty message

Revision ID: 559e4d05b552
Revises: 41c515076479
Create Date: 2019-03-13 09:55:40.980075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '559e4d05b552'
down_revision = '41c515076479'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wife',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wname', sa.String(length=20), nullable=True),
    sa.Column('wage', sa.Integer(), nullable=True),
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('users_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wife')
    # ### end Alembic commands ###
